fake_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    write_op_modes:
      - joint1
      - joint2
      - joint3
      - joint4
